### ISSUE TITLE
Panic in packages.

### ISSUE THREAD

**Issue by spankie** [ichtrojan/go-location#7]
Nice package Trojan

I looked at the codebase and noticed something, Some of the functions panic when an error occurs. I think the errors should be handled in a different way, preferably returned to the caller of the function. This is because, for example, I am building a web app that uses this package, I would not want my app to crash due to a `panic` when I can't retrieve a list of countries or state. Although this `panic` can be caught by using `recover` function, but that would cause some part of the code not to run.

I could send in a PR, for handling the errors as suggested if you want.

Thanks.

**Comment by ichtrojan** [comment]
Thanks David, please send in a PR.

**Comment by ichtrojan** [comment]
https://github.com/ichtrojan/go-location/pull/9
